---
creation_rules:
  - path_regex: kubernetes/.+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    age: age1drxxgueh9kgcqxq2mm2k2746wqx8zr48stnp9mp4xx20ue0et4gsrqdzcu
stores:
  yaml:
    indented: 2
