---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph2-osd1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph2-osd2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
