---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdi-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/kubevirt/cdi/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubevirt
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-cluster
spec:
  dependsOn:
    - name: cdi-operator
  interval: 1h
  path: ./kubernetes/apps/kubevirt/cdi/cdi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubevirt
