---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-dv
  namespace: default
spec:
  source:
    http:
      url: https://cloud-images.ubuntu.com/daily/server/noble/current/noble-server-cloudimg-amd64.img
  pvc:
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
