# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pihole-dns-secret
    namespace: network
stringData:
    pihole-password: ENC[AES256_GCM,data:oyVsQ66XxrEEXbT+oPI7aFIssMg1N8sCSenUfSq2RKfqyhW2HtLlcHnd6ak=,iv:u4ceiOtEwCm8g0ktZWhkJmtnEzaLg4PXuO0OIM0yLro=,tag:0JMtgMT1XZ1VyHXNxf5LrQ==,type:str]
sops:
    age:
        - recipient: age14y5zhjapyx4flp07ec8fey5lmvkrwp9pa3h5z9vyp546pf6lsc7sye0hej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU2VsOWxFQzBRd01GbGly
            a3Z1dTdZN2FqSi8waE9xTDRHaTRrczZ1QVNzCis2bWdSK0RwalIvZllpd3ZZTG5m
            UlZ0ZXQwWmZZZHlnSnhlYUZZMlZPejQKLS0tIGhUWWNORUZGMlRnczkxRUZoeGNk
            QW1zdlN4M1M4OWpyMHJvV0FvZUFNMk0KHqZvk7AcZVfD/95ZzkRCITSU/bV0sfzP
            AWfMNB9IRiZF23U+59f1KR1VC6iyuO/u60RQsd4Aw3YdR6rD8ryI/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T20:41:06Z"
    mac: ENC[AES256_GCM,data:MkT1ysOeMKHPnplysLnXgS5SY9sjvUCm+4cTGBrCH2rxsz83QcMbvo8MxuGu8bxezIeYs60mCSLXzWhHhWRfzz+hvvF69eiPF3kDexuCna4lwIui4wrPyYG1uX854DSoq0D+enHPyL49qO5OF73mCBU+Sd2GM5t5j7loM0llk7M=,iv:Ot5xg91bTzHECgLJzqLMOf5NblkHCKIKEDy7YgMFPg8=,tag:sbl0l99/tQ9UNMVD3IPgyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
