# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pihole-dns-secret
    namespace: network
stringData:
    pihole-password: ENC[AES256_GCM,data:ixUGYh57g5IqGjh9zA7tXJCI6ZVTi045xYWxE1HT+Ex1gJNE1kZYocQ5TCQ=,iv:+6ijFizJHSR+MX0ntKZWf8BjPBeRCzzsPGGjLjMfDwQ=,tag:nZSQV2yOvXrmB2XV3ppaRg==,type:str]
sops:
    age:
        - recipient: age1drxxgueh9kgcqxq2mm2k2746wqx8zr48stnp9mp4xx20ue0et4gsrqdzcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybGlORTRFTjlibjFRSmZo
            eERxK0NaNVdNUVJ5OUVNeU1USFJTYkRsMW1VCnZKK0pDRVBBdGZpNzB0anNLTDVW
            R0ZvcURTUjlRUmN1T29ZYkZFSjVsZ00KLS0tIHludkhXSDVoV2FNcGpERXpEY1dX
            UEFiRU1teWNCWVZjdW5FTXgvMmRBbWcK4bq6x4/3uYyECaiUqL59f9UtxxQpBVg8
            bYuFwFv+IrXbf9Of2qDbDauaTkXjlpORt4UtQqvks9jkdKssXbTKcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T22:24:34Z"
    mac: ENC[AES256_GCM,data:h/xu8diEyg2SC+ja5Tyk+zt2R4WLUFuwRJBhM70hBr1dUHi4QPQCk3X3ObAYtSkKws03xS8FHEd1BYyMeb1jEtR4x8F6sSLWRB+acM7JNfZ9Vdz1QaAZduTSLYBgtt3mtKkxJ9o6NXoBWlMqYGEpdqRK7O43ed1Q2HUcP9/8QHw=,iv:wfA9SsxxLvGJDq2W1zJLvQKTtYsasCLEdw/hLBm6Ob8=,tag:DXjbu3WEp/eL9qDIlv/f5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
