#yamllint diable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-issuer-secret
    namespace: cert-manager
type: Opaque
stringData:
    CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:pRrrqsBJhIVI29/QnEw6xAQx4IPM5Pnu/7UqGpvV+9aFahQ0tLPeJQ==,iv:rFy4jO4bDZ5zJ4tCqHnvO/jAC+ISNjzf+F0i2P1mHoU=,tag:qkOsa3btXweUAPoBKUyv+A==,type:str]
sops:
    age:
        - recipient: age1drxxgueh9kgcqxq2mm2k2746wqx8zr48stnp9mp4xx20ue0et4gsrqdzcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ0dVWDlhQWdQTnJnbHNW
            T082MExhV0pMK01pZ3FYNndzeWpPaEJnUWpvCnkrY0JNWmFhUlNLakFuQzdKeUE2
            TUtVZ0JCREFMYzVJSWt6ajFaSzhpVk0KLS0tIDUvYyt1aVFYeGYxQ0Nhd254Z2Va
            MytadlVnSUVIVFpzeThoN0pDaXpRWWsKIjlY37ceVnVQ0HbgWAVLFUyCC9Iwae/q
            vHbDiRqmzck39l6f1ZF46Ea0ll+MDZxUlFMW1nF723YgcGTSdNF6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T13:13:36Z"
    mac: ENC[AES256_GCM,data:Eu4Uo0BGlGSk4bhWSvp1QZVIOVCS0EIV3SYBNhVB+UaQUIlXXZ6WBWGf96ZQxulAqT8jWeP0GWde5H790+j9ZnaK8SZHIj9PBYZm9oF5kWlVR05WWKs2ABCMfgaCcaRk535BCMtWXM/cKz+jjwh5g6XfCR0q5fQLxPEnKhENJgU=,iv:6+/PcYVoA5Skvt+0Jm6th0bo4zaVej989U/04ed4rng=,tag:0alry8h+5/oeLdJqmK7iZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
